version: "3.7"

services:
  gitlab:
    image: gitlab/gitlab-ce:13.6.1-ce.0
    hostname: gitlab.ogontaro.com
    container_name: gitlab
    restart: always
    ports:
      - "80:80"
      - "2222:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      DEBUG: "true"
      TZ: Asia/Tokyo
      GITLAB_TIMEZONE: Tokyo
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.ogontaro.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.mailgun.org"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_user_name'] = "postmaster@mg.gitlab.com"
        gitlab_rails['smtp_password'] = "8b6ffrmle180"
        gitlab_rails['smtp_domain'] = "mg.gitlab.com"
        # Add any other gitlab.rb configuration here, each on its own line

volumes:
  gitlab-config:
  gitlab-log:
  gitlab-data:
