version: "3.7"

services:
  traefik:
    image: traefik:v2.3
    container_name: ogontaro_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./containers/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./containers/traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./containers/certs/:/certs/
    labels:
      - traefik.enable=true

  certbot:
    image: certbot/dns-route53
    container_name: ogontaro_certbot
    volumes:
      - ./containers/certs/:/etc/letsencrypt/
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --dns-route53 --agree-tos -m ${LETSENCRIPT_REGISTER_EMAIL} -d ogontaro.com -d *.ogontaro.com ; sleep 12h & wait $${!}; done;"
#    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot certonly --dns-route53 --agree-tos -m ${LETSENCRIPT_REGISTER_EMAIL} -d ogontaro.com -d *.ogontaro.com; sleep 12h & wait $${!}; done;"
    env_file:
      - .env

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.ogontaro.com`)"
