http:
  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
#    user-auth:
#      basicAuth:
#        users:
#          - "raf:$apr1$MTqfVwiE$FKkzT5ERGFqwH9f3uipxA1"

  routers:
    esxi:
      rule: "Host(`esxi.ogontaro.com`)"
      service: "esxi"
    rancher:
      rule: "Host(`rancher.ogontaro.com`)"
      service: "rancher"
    gitlab:
      rule: "Host(`gitlab.ogontaro.com`)"
      service: "gitlab"
    registry:
      rule: "Host(`registry.ogontaro.com`)"
      service: "gitlab"

  services:
    esxi:
      loadBalancer:
        servers:
          - url: "https://192.168.18.101:443"
    rancher:
      loadBalancer:
        servers:
          - url: "http://192.168.18.26:80"
    gitlab:
      loadBalancer:
        servers:
          - url: "http://192.168.18.25:31685/"
    registry:
      loadBalancer:
        servers:
          - url: "http://192.168.18.25:30257/"

tcp:
  routers:
    ssh_for_gitlab:
      entryPoints:
        - "ssh_for_gitlab"
      rule: "HostSNI(`*`)"
      service: ssh_for_gitlab

  services:
    ssh_for_gitlab:
      loadBalancer:
        servers:
          - address: "192.168.18.25:31431"

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
  stores:
    default:
      defaultCertificate:
        certFile: /certs/fullchain.pem
        keyFile: /certs/privkey.pem
