entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        domains:
          - main: "ogontaro.com"
            sans:
              - "*.ogontaro.com"

  ssh:
    address: :22
  sshudp:
    address: :22/udp

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik//dynamic.yml

api:
  dashboard: true
  insecure: true

#logLevel: DEBUG
